[package]
name = "lightyear_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
lightyear_shared = { path = "../shared" }
log = "0.4.20"

[dev-dependencies]
mock_instant = "0.3"
