[workspace]
resolver = "2"
members = [
  "examples",
  "macros",
  "lightyear",
  "vendor/wtransport/wtransport",
  "vendor/wtransport/wtransport-proto",
  "vendor/bitcode",
]
default-members = [
  "examples",
  "macros",
  "lightyear",
]
