[package]
name = "lightyear"
version = "0.2.0"
authors = ["Charles Bournhonesque <charlesbour@gmail.com>"]
edition = "2021"
rust-version = "1.65"
description = "Server-client networking library for the Bevy game engine"
readme = "../README.md"
repository = "https://github.com/cBournhonesque/lightyear"
keywords = ["bevy", "multiplayer", "networking", "netcode", "gamedev"]
categories = ["game-development", "network-programming"]
license = "MIT OR Apache-2.0"
exclude = ["/tests"]

[features]
debug = []
metrics = [
  "dep:metrics",
  "metrics-util",
  "metrics-tracing-context",
  "metrics-exporter-prometheus",
  "tokio",
]
mock_time = ["dep:mock_instant"]
webtransport = [
  "dep:wtransport",
  "tokio/sync",
  "wtransport/dangerous-configuration",
]
wtransport-cert = [
  "dep:ring",
  "dep:base64",
  "dep:rcgen",
  "dep:time",
]


[dependencies]
# utils
anyhow = "1.0"
chrono = "0.4.31"
cfg-if = "1.0"
derive_more = "0.99.17"
enum_delegate = "0.2"
enum_dispatch = "0.3"
mock_instant = { version = "0.3.1", optional = true }
paste = "1.0"
rand = "0.8"
ringbuffer = "0.15"
thiserror = "1.0.50"

# transport
# TODO: we are using this version because we need Certificate to be Cloneable. Upgrade when this is merged
wtransport = { version = "0.1.10", package = "wtransport_lightyear_patch", optional = true }
#wtransport = { git = "https://github.com/BiagioFesta/wtransport.git", branch = "master", optional = true }
ring = { version = "0.17.6", optional = true }
base64 = { version = "0.21.4", optional = true }
rcgen = { version = "0.11.3", optional = true }
time = { version = "0.3.1", optional = true }

# serialization
bitcode = { version = "0.4.0", package = "bitcode_lightyear_patch", features = [
  "serde",
] }
#bitcode = { git = "https://github.com/cBournhonesque/bitcode.git", branch = "cb/latest", features = [
#  "serde",
#] }
bytes = { version = "1.5", features = ["serde"] }
self_cell = "1.0"
serde = { version = "1.0.188", features = ["derive"] }

# netcode
chacha20poly1305 = { version = "0.10", features = ["std"] }
byteorder = "1.5.0"

# derive
#lightyear_macros = { path = "../macros" }
lightyear_macros = "0.1.0"

# tracing
tracing = "0.1.40"
tracing-log = "0.1.3"
tracing-subscriber = { version = "0.3.17", features = [
  "registry",
  "env-filter",
] }

# server
crossbeam-channel = { version = "0.5.8", features = [] }

# metrics
metrics = { version = "0.21", optional = true }
metrics-util = { version = "0.15", optional = true }
metrics-tracing-context = { version = "0.14", optional = true }
metrics-exporter-prometheus = { version = "0.12.1", optional = true, default-features = false, features = [
  "http-listener",
] }
tokio = { version = "1.34", features = [
  "rt",
  "rt-multi-thread",
  "net",
  "time",
], optional = true }

bevy = { version = "0.12", default-features = false }


[dev-dependencies]
derive_more = { version = "0.99", features = ["add", "mul"] }
mock_instant = { version = "0.3.1" }
tracing-subscriber = "0.3.17"
bitvec = "1.0"
