[package]
name = "lightyear"
version = "0.1.0"
edition = "2021"

[features]
debug = []
metrics = [
  "dep:metrics",
  "metrics-util",
  "metrics-tracing-context",
  "metrics-exporter-prometheus",
  "tokio",
]
mock_time = ["dep:mock_instant"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# utils
anyhow = "1.0"
chrono = "0.4.31"
enum_delegate = "0.2"
enum_dispatch = "0.3"
thiserror = "1.0.50"
paste = "1.0"
cfg-if = "1.0"
mock_instant = { version = "0.3.1", optional = true }


# serialization
bitcode = { git = "https://github.com/cBournhonesque/bitcode.git", branch = "cb/latest", features = [
  "serde",
] }
bytes = { version = "1.5", features = ["serde"] }
self_cell = "1.0"
serde = { version = "1.0.188", features = ["derive"] }

# netcode
chacha20poly1305 = { version = "0.10", features = ["std"] }
byteorder = "1.5.0"

# derive
lightyear_macros = { path = "../macros" }

# tracing
tracing = "0.1.40"
tracing-log = "0.1.3"
tracing-subscriber = { version = "0.3.17", features = [
  "registry",
  "env-filter",
] }

# server
crossbeam-channel = { version = "0.5.8", features = [] }

# metrics
metrics = { version = "0.21", optional = true }
metrics-util = { version = "0.15", optional = true }
metrics-tracing-context = { version = "0.14", optional = true }
metrics-exporter-prometheus = { version = "0.12.1", optional = true, default-features = false, features = [
  "http-listener",
] }
tokio = { version = "1.33", features = ["rt", "net", "time"], optional = true }

rand = "0.8"
ringbuffer = "0.15"
bevy = { version = "0.12", default-features = false }
taplo-cli = "0.8.1"
derive_more = "0.99.17"

[dev-dependencies]
derive_more = { version = "0.99", features = ["add", "mul"] }
mock_instant = { version = "0.3.1" }
tracing-subscriber = "0.3.17"
bitvec = "1.0"
