[package]
name = "lightyear"
version = "0.1.0"
edition = "2021"
authors = ["charlesbournhonesque <charlesbour@gmail.com>", "connorcarpenter <connorcarpenter@gmail.com>"]
workspace = ".."
description = "Networking library for bevy"
homepage = "https://github.com/cBournhonesque/lightyear"
repository = "https://github.com/cBournhonesque/lightyear"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[badges]
maintenance = { status = "actively-developed" }

[features]
default = ["webrtc"]
webrtc = ["dep:naia-socket-shared", "dep:naia-server-socket", "dep:naia-client-socket"]

[dependencies]
# internal
lightyear_derive = { version = "0.1.0", path = "../lightyear_derive" }
lightyear_serde = { version = "0.1.0", path = "../lightyear_serde" }

# transport
naia-socket-shared = { version = "0.15", optional=true }
naia-server-socket = { version = "0.15", optional=true }
naia-client-socket = { version = "0.15", optional=true }

# server
ring = { version = "0.16.15" }
fastrand = { version = "1.7.0" }

# bevy
#bevy_ecs = { version = "0.9", default-features=false }
#bevy_reflect = { version = "0.9", default-features=false}
bevy_ecs = { git = "https://github.com/bevyengine/bevy", default-features=false }
bevy_reflect = { git = "https://github.com/bevyengine/bevy", default-features=false }

# tools
cfg-if = { version = "1.0" }
tracing = { version = "0.1", default-features = false, features = ["std", "log"] }