[package]
name = "lightyear_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
lightyear_shared = { path = "../shared" }
crossbeam-channel = "0.5.8"
tracing = "0.1.39"
bevy = { version = "0.11", default-features = false}

[dev-dependencies]
mock_instant = "0.3"
