[package]
name = "lightyear_serde"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>", "Fedor <not.fl3@gmail.com>", "makepad <info@makepad.nl>"]
workspace = ".."
description = "Bit-level de/serialization for naia"
documentation = "https://docs.rs/naia-serde"
homepage = "https://github.com/naia-lib/naia"
repository = "https://github.com/naia-lib/naia"
keywords = ["serialization", "bit", "binary", "networking", "gamedev"]
categories = ["network-programming", "game-development", "wasm", "web-programming"]
license = "MIT OR Apache-2.0"
edition = "2021"

[badges]
maintenance = { status = "actively-developed" }

[features]

[dependencies]
lightyear_serde_derive = { version = "0.1.0", path = "derive" }
log = { version = "0.4" }
cfg-if = { version = "1.0" }
serde = { version = "1.0"}

[dev-dependencies]
serde = { version = "1.0", features=["derive"]}