[package]
name = "lightyear_derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
enum-as-inner = "0.6.0"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"]}
serde = { version = "1.0.188", features = ["derive"] }
anyhow = "1.0.75"
enum-kinds = "0.5"

[dev-dependencies]
lightyear_shared =  { path = ".." }


