[package]
name = "lightyear_shared"
version = "0.1.0"
edition = "2021"

[features]
debug = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
bitcode = { git = "https://github.com/cBournhonesque/bitcode.git", branch = "cb/latest", features = ["serde"] }
netcode = { git = "https://github.com/benny-n/netcode", tag = "v1.2.0" }
chacha20poly1305 = "0.10"
crossbeam = "0.8"
lazy_static = "1.4"
self_cell = "1.0"
bitvec = "1.0"
dyn-clone = "1.0"
bytes = { version = "1.5", features = ["serde"] }
enum_dispatch = "0.3"
rand = "0.8"
ringbuffer = "0.15"
serde = { version = "1.0.188", features = ["derive"] }
bevy = { version = "0.11", default-features = false }
paste = "1.0"
enum_delegate = "0.2"
enum-as-inner = "0.6.0"

tracing = "0.1"

lightyear_derive = {path = "derive" }
thiserror = "1.0.49"
byteorder = "1.5.0"

[dev-dependencies]
mock_instant = "0.3"
