[package]
name = "lightyear_shared"
version = "0.1.0"
edition = "2021"

[features]
debug = []
metrics = ["dep:metrics", "metrics-util", "metrics-tracing-context", "metrics-exporter-prometheus", "tokio"]
mock_time = ["mock_instant"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
bitcode = { git = "https://github.com/cBournhonesque/bitcode.git", branch = "cb/latest", features = ["serde"] }
netcode = { git = "https://github.com/benny-n/netcode", tag = "v1.2.0" }
chacha20poly1305 = "0.10"
crossbeam = "0.8"
lazy_static = "1.4"
self_cell = "1.0"
bitvec = "1.0"
dyn-clone = "1.0"
bytes = { version = "1.5", features = ["serde"] }
enum_dispatch = "0.3"
rand = "0.8"
ringbuffer = "0.15"
serde = { version = "1.0.188", features = ["derive"] }
bevy = { version = "0.12", default-features = false }
paste = "1.0"
enum_delegate = "0.2"
enum-as-inner = "0.6.0"
tracing-subscriber = "0.3.17"
cfg-if = "1.0"

metrics = { version = "0.21", optional = true }
metrics-util = { version = "0.15", optional = true }
metrics-tracing-context = { version = "0.14", optional = true }
metrics-exporter-prometheus = { version = "0.12.1", optional = true, default-features = false, features = ["http-listener"] }
tokio = { version = "1.33", features = ["rt", "net", "time"], optional = true}

tracing = "0.1"

lightyear_derive = {path = "derive" }
thiserror = "1.0.49"
byteorder = "1.5.0"
chrono = "0.4.31"

mock_instant = { version = "0.3", optional = true }

[dev-dependencies]
mock_instant = "0.3"
tracing-subscriber = "0.3.17"
