[package]
name = "lightyear_shared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
bitcode = "0.4"
bytes = { version = "1.5", features = ["serde"] }
enum_dispatch = "0.3"
rand = "0.8"
ringbuffer = "0.15"
serde = { version = "1.0.188", features = ["derive"] }

lightyear_derive = {path = "../derive"}

[dev-dependencies]
mock_instant = "0.3"
