[package]
name = "leafwing-inputs"
version = "0.0.0"
authors = ["Charles Bournhonesque <charlesbour@gmail.com>"]
edition = "2021"
rust-version = "1.65"
publish = false

[features]
metrics = ["lightyear/metrics", "dep:metrics-exporter-prometheus"]
mock_time = ["lightyear/mock_time"]

[dependencies]
bevy_framepace = "0.14.1"
bevy-fps-counter = "0.3.0"
leafwing-input-manager = "0.11.2"
bevy_xpbd_2d = { git = "https://github.com/Jondolf/bevy_xpbd", features = [
  "serialize",
] }
lightyear = { path = "../../lightyear", features = [
  "webtransport",
  "render",
  "leafwing",
  "xpbd_2d",
] }
serde = { version = "1.0.188", features = ["derive"] }
anyhow = { version = "1.0.75", features = [] }
tracing = "0.1"
tracing-subscriber = "0.3.17"
bevy = { version = "0.12", features = ["bevy_core_pipeline"] }
derive_more = { version = "0.99", features = ["add", "mul"] }
rand = "0.8.1"
clap = { version = "4.4", features = ["derive"] }
mock_instant = "0.3"
metrics-exporter-prometheus = { version = "0.12.1", optional = true }
bevy-inspector-egui = "0.21.0"
tokio = { version = "1.34.0", features = ["rt", "macros"] }
